# Generated by Django 3.2.9 on 2021-12-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='phone',
            field=models.CharField(max_length=13),
        ),
    ]
